In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('seattle-weather.csv')
df.head(4)

,date,precipitation,temp_max,temp_min,wind,weather
0,2012-01-01,0.0,12.8,5.0,4.7,drizzle
1,2012-01-02,10.9,10.6,2.8,4.5,rain
2,2012-01-03,0.8,11.7,7.2,2.3,rain
3,2012-01-04,20.3,12.2,5.6,4.7,rain


In [4]:
df.weather.unique()

array(['drizzle', 'rain', 'sun', 'snow', 'fog'], dtype=object)

In [5]:
df.shape

(1461, 6)

In [6]:
df.dtypes

date              object
precipitation    float64
temp_max         float64
temp_min         float64
wind             float64
weather           object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


In [8]:
df.describe()

,precipitation,temp_max,temp_min,wind
count,1461.000000,1461.000000,1461.000000,1461.000000
mean,3.029432,16.439083,8.234771,3.241136
std,6.680194,7.349758,5.023004,1.437825
min,0.000000,-1.600000,-7.100000,0.400000
25%,0.000000,10.600000,4.400000,2.200000
50%,0.000000,15.600000,8.300000,3.000000
75%,2.800000,22.200000,12.200000,4.000000
max,55.900000,35.600000,18.300000,9.500000


In [9]:
df.weather.value_counts()

weather
rain       641
sun        640
fog        101
drizzle     53
snow        26
Name: count, dtype: int64

In [10]:
df.isnull().sum()

date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [12]:
# PREPROCESSING PORR
# SPLIT THE DATA INTRO INPUT AND TARGET
X=df.iloc[:,1:-1]  
Y=df.iloc[:,-1:]

In [13]:
Y

,weather
0,drizzle
1,rain
2,rain
3,rain
4,rain
...,...
1456,rain
1457,rain
1458,fog
1459,sun


In [31]:
# APPLY LABEL ENCODING ONTO WEATHER COLUMN
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
Y.iloc[:,0]=LE.fit_transform(Y)
Y


C:\Users\swbhi\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,weather
0,0
1,2
2,2
3,2
4,2
...,...
1456,2
1457,2
1458,1
1459,4


In [32]:
# trace test split 
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest=train_test_split(X, Y, test_size=0.25, random_state=0)
print(Xtrain.shape, ytrain.shape)
print(Xtest.shape, ytest.shape)

(1095, 4) (1095, 1)
(366, 4) (366, 1)


In [40]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Convert ytrain to discrete class labels if it contains continuous values
# Option 1: If ytrain should be classification data but is in wrong format
ytrain = ytrain.astype(int)  # Convert float labels to integers if appropriate

# Option 2: If you actually need regression rather than classification
# from sklearn.neighbors import KNeighborsRegressor
# KNN = KNeighborsRegressor(n_neighbors=5, p=2)

# Original classification approach with proper data types
KNN = KNeighborsClassifier(n_neighbors=5, p=2)
KNN.fit(Xtrain, ytrain)

C:\Users\swbhi\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [41]:
KNeighborsClassifier()

KNeighborsClassifier()

In [42]:
# testing
Ypredict=KNN.predict(Xtest)
Ypredict[:10]

array([4, 2, 2, 4, 0, 2, 2, 2, 4, 2])

In [25]:
Y.dtypes

weather    object
dtype: object

In [17]:
X

,precipitation,temp_max,temp_min,wind
0,0.0,12.8,5.0,4.7
1,10.9,10.6,2.8,4.5
2,0.8,11.7,7.2,2.3
3,20.3,12.2,5.6,4.7
4,1.3,8.9,2.8,6.1
...,...,...,...,...
1456,8.6,4.4,1.7,2.9
1457,1.5,5.0,1.7,1.3
1458,0.0,7.2,0.6,2.6
1459,0.0,5.6,-1.0,3.4


# KNN ALGORITHM

-it is  a non parametric algorithm which doesnt make any assumption
- it as one of simplest and easy to implementable algorithm
- it is also called s Lazy algorithm, as it does nt learns anything dirung training phase

 # KNN STEPS

-compute the distance btw test point vs all training samples
- (use any distance measures like Euclidien,Manhattan,minkowski)
- arrange the distance computed in ascending order
- select the k value
- vote for majority
- class having higher votes is the outcome 

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix

# First, ensure both arrays have the same format and label types
# Convert both arrays to the same data type if needed
ytest = ytest.astype(int)  # or str, depending on your data
Ypredict = Ypredict.astype(int)  # use the same type as ytest

# Make sure Ypredict only contains classes that are in ytest
# You might need to filter or map values if this is the issue

# Then create the confusion matrix
cm = confusion_matrix(ytest, Ypredict)
cm

array([[  1,   1,   1,   0,   8],
       [  3,   4,   4,   0,  20],
       [  1,   4, 130,   0,  20],
       [  0,   0,   3,   2,   1],
       [  6,  10,  18,   0, 129]])

In [45]:
df.weather.value_counts

weather
rain       641
sun        640
fog        101
drizzle     53
snow        26
Name: count, dtype: int64

 # Standardized data

In [ ]:
from sklearn.preprocessing import StandardScalar
SS=StandardScalar()
X.iloc[:,:

In [ ]:
from sklearn.neighbors import KNeighbors

# decision trees

Decision  trees works on the concept of recursive partioning of the data
- by using best attribute to make decision
- i want to buy mobile,what features
 write any 5 features you think are required
- camera
- price
- processor
- brand
- ram

 # Building decision tree algorithm

In [46]:
from sklearn.tree import DecisionTreeClassifier
DTC=DecisionTreeClassifier(criterion='entropy', random_state=0)

# train the model
DTC.fit(Xtrain, ytrain)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [51]:
# testing 
Ypredict=DTC.predict(Xtest)
Ypredict[:10]

array([4, 0, 2, 4, 4, 2, 2, 2, 4, 2])

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(ytest, Ypredict)
cm

array([[  1,   2,   1,   0,   7],
       [  6,   8,   1,   0,  16],
       [  0,   1, 140,   4,  10],
       [  0,   0,   3,   3,   0],
       [ 19,  24,   9,   0, 111]])

In [49]:
accuracy_score(ytest, Ypredict)

0.7185792349726776